#!/usr/bin/env bash

# garage get ruby20 == garage/ruby20
# garage get juniorz/ruby20

# TODO:
# garage get ruby20 <docker build command>

image_name="$(image_from_garage $1)"

debug_msg "Get image: $image_name"

#if [[ $(docker images -q $image_name | wc -l) -eq 0 ]]; then
#  if [[ "$image_name" == "garage/"* ]]; then
#    (docker images | grep -q "garage/base") || docker pull garage/base 2> /dev/null
#  fi

  docker pull $image_name 2> /dev/null

  if [[ $? -eq 0 ]]; then
    garage wrapper $image_name
  else
    echo "Failed to download $image_name"
  fi
#else
#  echo "Nothing to do!"
#fi
