#!/usr/bin/env bash

# garage wrapper ruby20

#TODO: make /garage volume configurable
create_wrapper_for() {
  image_name=$1
  cmd=$2

  wrapper_dir=$GARAGE_ROOT/wrappers/$image_name

  mkdir -p $wrapper_dir
  cat <<EOS > "$wrapper_dir/$cmd"
#!/bin/bash

garage run $image_name $cmd \${@}
EOS

  chmod 0755 $wrapper_dir/$cmd
}

create_image_wrappers() {
  image_name=$1

  for cmd in $(garage provides $image_name); do
    create_wrapper_for $image_name $cmd
  done
}

#TODO: check if image is installed?
create_image_wrappers $(image_from_garage $1)
